eafit-apolo/apolo-users

docs/source/software/applications/lammps/lammps-22Aug2018/index.rst
Improving documentation for extra packages.
=> Updating lammps documentation

docs/source/software/applications/pargenes/pargenes-master/index.rst
=> update pargenes example

docs/source/software/scientific_libraries/GMP/6.1.2/index.rst, docs/source/software/scientific_libraries/GMP/index.rst
=> gmp update fix error

docs/source/software/applications/gromacs-ls/gromacs-ls-4.5.5/index.rst, docs/source/software/applications/gromacs-ls/index.rst, docs/source/software/applications/index.rst, docs/source/software/scientific_libraries/LAPACK/3.5.0/index.rst, docs/source/software/scientific_libraries/LAPACK/index.rst, docs/source/software/scientific_libraries/index.rst
=> Gromacs ls

docs/source/software/applications/Lmod/8.2.7/index.rst, docs/source/software/applications/Lmod/index.rst, docs/source/software/applications/index.rst
=> Lmod documentation

docs/source/software/managementsoftware/slurm/src/submit/sbatch_options.csv, docs/source/software/managementsoftware/slurm/submit.rst
All in **Submitting jobs** section.
* Added documentation on SBATCH options' subsection.
* Created a subsection. Namely 'Constraining Features'.
=> Documented SLURM jobs' features

docs/source/gettingstarted/configure_vpn.rst
El objetivo de este pull-request es practicar  git un poco. 
Y proponer dividir la seccion de linux en dos partes, la primera (**Connect through GUI**) explicando como interactuar con la VPN a traves de una interfaz grafica, la segunda parte (**Connect through terminal**) explicando como realizar el mismo proceso pero sin acceso a una interfaz grafica.
=> VPN Documentation

docs/source/software/accelerators/cuda-mps/8.0/index.rst, docs/source/software/accelerators/cuda-mps/index.rst, docs/source/software/accelerators/index.rst, docs/source/software/index.rst
Accelerators documentation, specially about cuda-8.0
=> Accelerators

docs/source/software/programminglanguages/R/index.rst, docs/source/software/programminglanguages/R/packrat/index.rst
Sorry about the name of the branch, i made a mistake.
=> Packrat documentation

.pre-commit.yml
- Add pre-commit configuration file
- Add hook for removing trailing spaces
- Add hook for removing extra lines
- Add hook for checking yaml syntax
=> (feat): Add pre-commit framework

docs/source/software/applications/clustalw/2.1/index.rst, docs/source/software/applications/clustalw/index.rst, docs/source/software/applications/index.rst
- Add Clustalw entry in index.rst under applications directory
- Add Clustalw index
- Add Clustalw 2.1 directory and its documentation
=> (doc): Add Clustalw entry and its documentation

docs/source/software/applications/index.rst, docs/source/software/applications/kraken/2.1.0/index.rst, docs/source/software/applications/kraken/index.rst
- Add Kraken entry in index.rst under applications directory
- Add Kraken index
- Add Kraken 2.1.0 directory and its documentation
=> (doc): Add Kraken entry and its documentation

docs/source/software/applications/index.rst, docs/source/software/applications/prank/170427/index.rst, docs/source/software/applications/prank/index.rst
- Add Prank entry in index.rst under applications directory
- Add Prank index
- Add Prank 170427 directory and its documentation
=> (doc): Add Prank entry and its documentation

docs/source/software/applications/index.rst
- Sort applications index alphabetically.
- Delete a duplicate entry
=> (style): Sort applications index

.github/workflows/pre-commit.yml
Add github action for running pre-commit framework on any
push to a branch with the following structure <type>/<description>
=> (feat): Add pre-commit github action

docs/source/software/applications/OpenFOAM/index.rst, docs/source/software/applications/OpenFOAM/v2006/index.rst
Added documentatio for OpenFOAM v2006 Installation
=> (feat) Added docs for OpenFOAM v2006 installation

docs/source/software/programminglanguages/R/R-4.0.3/index.rst, docs/source/software/programminglanguages/R/index.rst
(feat) Added R 4.0.3 installation in Apolo
* Installation in-cluster
* Installation in anaconda
=> (feat): Added R 4.0.3 installation in Apolo

docs/source/software/applications/mrBayes/index.rst, docs/source/software/applications/mrBayes/mr.3.2.6/index.rst, docs/source/software/applications/mrBayes/mr.3.2.7/index.rst
(feat) Added Mrbayes 3.2.7 installation in Apolo
- Installation in-cluster
=> (feat): Added Mrbayes 3.2.7 installation in Apolo

docs/source/software/programminglanguages/R/R-4.0.3/index.rst
Added instruction to when no package is available in conda, use R repository.
=> (feat): added instruction when no package is available in conda.

docs/source/software/applications/BEAST2/2.6.4/index.rst, docs/source/software/applications/BEAST2/index.rst
- Added documentation for installing BEAST2.6.4 in ``BEAST2/2.6.4/index.rst``
- Added reference to the documentation of the new version in the parent index.
=> (doc): Added documentation for BEAST2.6.4

docs/source/software/applications/BEAST2/2.6.3/index.rst, docs/source/software/applications/BEAST2/index.rst
Added BEAST2 2.6.3 installation in Apolo-ii and bug correction
=> (Feat):  Added BEAST2 2.6.3 installation in Apolo-ii

docs/source/software/applications/index.rst, docs/source/software/applications/phylonet/3.8.0/index.rst, docs/source/software/applications/phylonet/index.rst
```
$WWWWWWWg_
^WWWWWWWWg
WWWWWWWWg
$WWWWWWWW_
$WWWWWWWWg
^WWWWWWWWW
gWWWWWWWWW_
_gWWWWWWWWWWWg
_WWWWWWWWWWWWWWW
gWWWWWWWWMWWWWWWWW_
_WWWWWWWWW^ ^WWWWWWWWg
gWWWWWWWWW     $WWWWWWWW_
gWWWWWWWWWWWg   gWWWWWWWWW_
_WWWWWWWWWWWWWWW gWWWWWWWWWWWg
gWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_
_____ gWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW_
gWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|WWWWWWWWWg
WWWWWWWWWWWWWWWWW^^MWWWWWWWWWWWWWWWWWWWWWWWWWWW_
WWWWWWWWWWWWWWWM^       ^^^^^^^^^^$WWWWWWWWWWWWWW_
WWWWWWWWWWWWWWW                     ^MWWWWWWWWWWWW
$WWWWWWWWWWWWW$                       $WWWWWWWWWWW
$WWWWWWWWWWWM                         WWWWWWWWWWF
^MWWWWWWWM^                           ^WWWWWWM^ 
```
:)
=> (doc): Added documentation for phylonet 3.8.0

docs/source/software/scientific_libraries/Jasper/Jasper-3.0.3/index.rst, docs/source/software/scientific_libraries/Jasper/index.rst
=> Doc: Jasper lib installation documentation version 3.0.3

docs/source/software/scientific_libraries/GMP/6.2.1/index.rst, docs/source/software/scientific_libraries/GMP/index.rst
- GMP for gcc 9.3.0 and gcc 11.2.0
=> Doc: GMP installation documentation version 6.2.1

docs/source/software/applications/crystal/crystal17/1.0.2/index.rst, docs/source/software/applications/crystal/crystal17/index.rst, docs/source/software/applications/crystal/index.rst
Created documentation for scientific application crystal17
which it's demo version was recently installed
- Added crystal index.rst reference in the toctree at the level software/applicactions
- Main index.rst for crystal17
- New file for crystal17v 1.0.2
=> (doc): Create documentation for crystal17

docs/source/software/applications/gurobi/gurobi-9.5.0/index.rst, docs/source/software/applications/gurobi/index.rst
Documentation of gurobi-9.5.0 installation
=> Doc/gurobi 9.5.0

docs/source/software/scientific_libraries/NetCDF/4.8.0-disable-netcdf-4/index.rst, docs/source/software/scientific_libraries/NetCDF/index.rst
=> Doc/netcdf 4.8.0 disable netcdf 4

docs/source/software/applications/wrf/4.2/index.rst, docs/source/software/applications/wrf/4.2/installation.rst, docs/source/software/applications/wrf/index.rst
- WRF version 4.2 installation documentation including dependencies
=> WRF version 4.2 installation documentation

docs/source/software/applications/mpich/3.4.2/index.rst, docs/source/software/applications/mpich/index.rst
=> Doc: Mpich installation documentation version 3.4.2

docs/source/software/virtualization/vmwareesxi/ovftool/ovftool430/index.rst
Solved a typo.
- Changed version from 4.0.0 to 4.3.0.
=> (fix): Fix version of OVF tool used.
